-- ─────────────────────────────────────────────────────────────────────────────
-- schema.sql is no longer the source of truth.
--
-- Every table, index, and RLS policy lives in supabase/migrations/.
-- Apply them in numeric order:
--
--   001_audit_log.sql   — append-only audit trail
--   002_user_state.sql  — user_snaptrade, user_state, user_keys
--   003_plaid.sql       — plaid_tokens, plaid_accounts
--
-- To run them:
--
--   • Hosted Supabase project:
--       `npx supabase db push`             (if you've linked the CLI)
--     or paste each file into Supabase → SQL Editor in order.
--
--   • Self-hosted / local:
--       `psql $DATABASE_URL -f supabase/migrations/001_audit_log.sql`
--       `psql $DATABASE_URL -f supabase/migrations/002_user_state.sql`
--       `psql $DATABASE_URL -f supabase/migrations/003_plaid.sql`
--
-- After applying, hit /api/admin/db-status (signed in as OWNER_EMAIL) to
-- verify every expected table is present without leaving the app.
-- ─────────────────────────────────────────────────────────────────────────────
