// The BACKLOG.md → Admin Center summary (scripts/gen-backlog-summary.mjs).
//
// The generated JSON is committed AND regenerated by `npm run build`, so these
// assertions are really about the parser surviving edits to BACKLOG.md. If
// someone restructures its headings, the admin tile would quietly render an
// empty or wrong list — the generator hard-fails on zero buckets, and this
// pins the invariants that a partial parse would break instead.
import { describe, it, expect } from 'vitest'
import summary from '../generated/backlog.json'

const byKey = Object.fromEntries(summary.buckets.map(b => [b.key, b]))

describe('backlog summary — structure', () => {
  it('parses every bucket the file defines', () => {
    // F fixes · G growth · N features · M migrations · P parked · O owner
    // · S shipped · X obsolete · U unverified
    for (const k of ['F', 'G', 'N', 'M', 'P', 'O', 'S', 'X', 'U']) {
      expect(byKey[k], `bucket ${k} missing`).toBeDefined()
    }
  })

  it('gives every bucket a human title and at least one item', () => {
    for (const b of summary.buckets) {
      expect(b.title.length, `${b.key} has no title`).toBeGreaterThan(0)
      expect(b.items.length, `${b.key} has no items`).toBeGreaterThan(0)
    }
  })

  it('gives every item a well-formed id matching its bucket', () => {
    for (const b of summary.buckets) {
      for (const item of b.items) {
        expect(item.id).toMatch(/^[A-Z]\d+$/)
        expect(item.id[0], `${item.id} filed under ${b.key}`).toBe(b.key)
        expect(item.title.length).toBeGreaterThan(0)
      }
    }
  })
})

describe('backlog summary — counts must not lie', () => {
  it('marks S and X as archives with nothing open', () => {
    // Regression guard: the first version reported "Already shipped" as 5/5
    // OPEN and "Obsolete" as 2/2 open, because those headings carry no ✅ —
    // the bucket itself is the marker.
    for (const k of ['S', 'X']) {
      expect(byKey[k].archive, `${k} should be an archive`).toBe(true)
      expect(byKey[k].open, `${k} should have 0 open`).toBe(0)
      expect(byKey[k].items.every(i => i.done)).toBe(true)
    }
  })

  it('does not mark working buckets as archives', () => {
    for (const k of ['F', 'G', 'N', 'O']) {
      expect(byKey[k].archive).toBe(false)
    }
  })

  it('keeps open + done consistent with total in every bucket', () => {
    for (const b of summary.buckets) {
      expect(b.total).toBe(b.items.length)
      expect(b.open).toBe(b.items.filter(i => !i.done).length)
    }
  })

  it('strips the done marker out of display titles', () => {
    for (const b of summary.buckets) {
      for (const item of b.items) {
        expect(item.title, `${item.id} still shows a raw marker`).not.toMatch(/✅/)
      }
    }
  })
})

describe('backlog summary — payload size', () => {
  it('stays far smaller than the 176KB source it summarizes', () => {
    // The whole point: headings only. If this ever approaches the markdown's
    // size, someone started including item bodies and it's shipping to clients.
    expect(JSON.stringify(summary).length).toBeLessThan(60_000)
  })
})
